version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: priceboard_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
volumes:
  pg_data: