version: "3.8"
services:
  node-app:
    build: .
    image: node-with-sqlite
    ports:
      - "3000:3000"

  sqliteweb:
    image: tomdesinto/sqliteweb
    ports:
      - "8080:8080"
    volumes:
      - ./priceboard.db:/db/priceboard.db
    command: priceboard.db