services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: server
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev